name: sasl_scram
description: A Package providing sasl/scram authentication. Both scram-1 and scram-256 are managed.
version: 0.1.1
homepage: https://github.com/mongo-dart/sasl_scram

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  buffer: ^1.1.0
  crypto: ^3.0.0
  collection: ^1.15.0
  saslprep: ^1.0.2

dev_dependencies:
  #pedantic: ^1.10.0
  test: ^1.16.0
  lints: ^2.0.0

